feat/#5 room get
so2zy/so2zy_BE pull request #24
Opened 2023-11-22 06:30 UTC by YurimYang

## 핵심 변경사항

- 숙소 상세 조회 기능 구현 완료
   └ 객실 상세 조회 => 숙소 상세 조회  (room패키지 => accommodation패키지)

- 숙소 상세 조회 기능 Controller, Service, Repository Unit Test 완료

## 특이 사항

- 무한순환참조 문제 확인 및 해결방안
 https://github.com/so2zy/so2zy_BE/discussions/23#discussion-5878755

## Issue Link - #5

2023-11-22 08:17 UTC, Nine-JH requested changes
고생하셨습니다! 몇몇 코멘트 남겼으니까 궁금하신점은 답글 달아주세요!

2023-11-22 08:17 UTC, Nine-JH commented on src/test/java/com/aroom/domain/accommodation/repository/AccommodationRepositoryTest.java
> +@AutoConfigureTestDatabase(connection = EmbeddedDatabaseConnection.H2)
1. 이미 설정정보에서 H2 Inmemory를 사용하고 있기 때문에 `@AutoConfigureTestDatabase`는 필요하지 않습니다.
2. `@DataJpaTest` 내부적으로 `@AutoConfigureTestDatabase` 기능을 가지고 있습니다. 추가적으로 build.gradle 에서 가지는 driver class Dependency을 자동적으로 감지해서 사용하기 때문에 굳이 명시할 필요가없습니다.

2023-11-22 08:17 UTC, Nine-JH commented on src/test/java/com/aroom/domain/accommodation/repository/AccommodationRepositoryTest.java
> +        entityManager.createNativeQuery("SET REFERENTIAL_INTEGRITY TRUE").executeUpdate();
DB 테스트에 대한 고려를 정말 많이 한것이 느껴지네요 👍 
다만 현재 테스트에서는 해당 로직이 필요한지는 의문이네요!

2023-11-23 02:47 UTC, YurimYang commented on .env.sample
깃허브 상에서 delete file을 하면 될까요 ?

2023-11-23 02:47 UTC, YurimYang commented on src/test/java/com/aroom/domain/accommodation/repository/AccommodationRepositoryTest.java
> +@AutoConfigureTestDatabase(connection = EmbeddedDatabaseConnection.H2)
아하 설명 감사합니다 ~! 수정하도록 하겠습니다 👍

2023-11-23 02:47 UTC, YurimYang commented on src/test/java/com/aroom/domain/accommodation/repository/AccommodationRepositoryTest.java
> +        entityManager.createNativeQuery("SET REFERENTIAL_INTEGRITY TRUE").executeUpdate();
생각해보니, 저희가 room을 save하는 로직은 없으니 beforeEach구문 로직을 실행하지 않아도 될것같습니다. 언급해주셔서 감사합니다 👍

2023-11-23 03:18 UTC, YurimYang commented on src/main/java/com/aroom/domain/accommodation/exception/AccommodationNotFoundException.java
만약 ServiceException을 상속받는다면, 
ErrorCode에 Error Message를 작성해줘야하고 
Domain내부의 Exception들이 모두 Global로 빠지게 되어서 Domain설계에 어긋나지 않을까요?

2023-11-23 03:18 UTC, YurimYang commented on src/main/java/com/aroom/domain/accommodation/controller/AccommodationRestControllerAdvice.java
위와 같은 의견입니다 !

2023-11-23 04:57 UTC, Nine-JH commented on .env.sample
음 제가 그 기능을 써보진 않아서 모르겠네요 ㅋㅋㅋ

2023-11-23 05:06 UTC, Nine-JH commented on src/main/java/com/aroom/domain/accommodation/exception/AccommodationNotFoundException.java
1. Exception이 굳이 global로 빠질 필요는 없습니다. 단지 의존관계만 추가가 되는 형식입니다.
2. ErrorCode에 각각의 메시지를 작성해주어야 하는 점에서는 그런 걱정이 이해가 가네요. 이건 선택의 영역같습니다 일정부분을 포기하고 관리포인트를 응집할 것이냐, 아니냐의 차이일뿐 그 이상은 아닌 것 같아요

2023-11-23 05:29 UTC, YurimYang commented on src/main/java/com/aroom/domain/accommodation/controller/AccommodationRestController.java
> +    private final AccommodationService roomService;
제가 Room 패키지에서 Accommodation으로 변경하면서 미처 바꾸지 못했네요! 감사합니다 ~

2023-11-23 05:29 UTC, YurimYang commented on src/main/java/com/aroom/domain/accommodation/dto/response/AccommodationResponseDTO.java
> +    private List<Room> roomList;
DTO로 감싸서 다시 해보겠습니다 :) 감사합니다 !

2023-11-23 07:32 UTC, YurimYang commented on .env.sample
commit을 추후에 너무 많이 진행해서 이번 #5 merge 이후, env.sample. 다시 develop에 올리도록 하겠습니다..! 죄송합니다😓

2023-11-23 07:55 UTC, Nine-JH approved these changes

2023-11-23 09:52 UTC, merged